---

ansible_user: root
ansible_python_interpreter: /usr/bin/python

# NTP config
ntp_manage_config: true
ntp_servers: ["pool.ntp.org"]

# Proxmox config
pve_repository: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
pve_release_key_id: 7BF2812E8A6E88E0

pve_check_for_kernel_update: true
pve_reboot_on_kernel_update: true
pve_remove_old_kernels: true
pve_run_proxmox_upgrades: true

# Cluster specific config
pve_group: hypervisors
pve_cluster_clustername: nyc01
# we handle it separately
pve_remove_subscription_warning: false
pve_cluster_enabled: true
# we need to let both hosts be able to ssh to each other
pve_manage_ssh: true
pve_storages:
  - name: luna
    type: nfs
    content: ["images", "iso", "snippets", "rootdir", "backup", "vztmpl"]
    server: 192.168.0.2
    export: /volume2/ProxmoxDataStore

sdn_dependencies:
  - libpve-network-perl
  - ifupdown2

pve_vxlan_zones:
  - name: myvxlan1
    peers: "{{ groups['hypervisors'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join(',') }}"
    ipam: pve
    mtu: 1450  # we need to leave 50 bytes for vxlan header
    nodes: "{{ groups['hypervisors'] | map('extract', hostvars, ['ansible_hostname']) | join(',') }}"
  - name: myvxlan2
    peers: "{{ groups['hypervisors'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join(',') }}"
    ipam: pve
    mtu: 1450  # we need to leave 50 bytes for vxlan header
    nodes: "{{ groups['hypervisors'] | map('extract', hostvars, ['ansible_hostname']) | join(',') }}"
  - name: myvxlan3
    peers: "{{ groups['hypervisors'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join(',') }}"
    ipam: pve
    mtu: 1450  # we need to leave 50 bytes for vxlan header
    nodes: "{{ groups['hypervisors'] | map('extract', hostvars, ['ansible_hostname']) | join(',') }}"
  - name: myvxlan4
    peers: "{{ groups['hypervisors'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join(',') }}"
    ipam: pve
    mtu: 1450  # we need to leave 50 bytes for vxlan header
    nodes: "{{ groups['hypervisors'] | map('extract', hostvars, ['ansible_hostname']) | join(',') }}"
  - name: myvxlan5
    peers: "{{ groups['hypervisors'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join(',') }}"
    ipam: pve
    mtu: 1450  # we need to leave 50 bytes for vxlan header
    nodes: "{{ groups['hypervisors'] | map('extract', hostvars, ['ansible_hostname']) | join(',') }}"
  - name: myvxlan6
    peers: "{{ groups['hypervisors'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join(',') }}"
    ipam: pve
    mtu: 1450  # we need to leave 50 bytes for vxlan header
    nodes: "{{ groups['hypervisors'] | map('extract', hostvars, ['ansible_hostname']) | join(',') }}"
  - name: myvxlan7
    peers: "{{ groups['hypervisors'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join(',') }}"
    ipam: pve
    mtu: 1450  # we need to leave 50 bytes for vxlan header
    nodes: "{{ groups['hypervisors'] | map('extract', hostvars, ['ansible_hostname']) | join(',') }}"
  - name: myvxlan8
    peers: "{{ groups['hypervisors'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join(',') }}"
    ipam: pve
    mtu: 1450  # we need to leave 50 bytes for vxlan header
    nodes: "{{ groups['hypervisors'] | map('extract', hostvars, ['ansible_hostname']) | join(',') }}"
  - name: myvxlan9
    peers: "{{ groups['hypervisors'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join(',') }}"
    ipam: pve
    mtu: 1450  # we need to leave 50 bytes for vxlan header
    nodes: "{{ groups['hypervisors'] | map('extract', hostvars, ['ansible_hostname']) | join(',') }}"

pve_vnets:
  - name: vnet01
    zone: myvxlan1
    alias: vnet01
    tag: 10000
  - name: vnet02
    zone: myvxlan2
    alias: vnet02
    tag: 20000
  - name: vnet03
    zone: myvxlan3
    alias: vnet03
    tag: 30000
  - name: vnet04
    zone: myvxlan4
    alias: vnet04
    tag: 40000
  - name: vnet05
    zone: myvxlan5
    alias: vnet05
    tag: 50000
  - name: vnet06
    zone: myvxlan6
    alias: vnet06
    tag: 60000
  - name: vnet07
    zone: myvxlan7
    alias: vnet07
    tag: 70000
  - name: vnet08
    zone: myvxlan8
    alias: vnet08
    tag: 80000
  - name: vnet09
    zone: myvxlan9
    alias: vnet09
    tag: 90000
