---

- hosts: storage
  gather_facts: true

  tasks:
    - name: Deploy Minio
      block:
        - name: Create destionation directory
          file:
            path: "{{ path_to_dockercomposefiles }}/minio"
            state: directory
            mode: '0755'
          become: true
        - name: Copy docker-compose file to remote host
          template:
            src: "{{ playbook_dir }}/templates/docker-compose-minio.yml.j2"
            dest: "{{ path_to_dockercomposefiles }}/minio/docker-compose.yml"
            mode: 0640
            owner: mohitsharma44
            group: administrators
          become: true
        - name: Deploy minio stack
          docker_compose:
            project_src: "{{ path_to_dockercomposefiles }}/minio"
            files:
              - docker-compose.yml
            restarted: true
            remove_orphans: true
