---

- hosts: 127.0.0.1
  gather_facts: true
  tasks:
    - name: Decrypt the private keys
      block:
        - name: Find all sensitive files
          find:
            paths: "{{ ler53_account_key_dir }}"
            file_type: file
            patterns:
              - "{{ fqdn }}.key"
            recurse: true
            depth: 2
          register: keys

        - name: Decrypt the private keys
          command: "ansible-vault decrypt {{ item.path }} --vault-password-file {{ playbook_dir | dirname }}/.vault_password"
          with_items: "{{ keys.files | flatten(levels=1) }}"
          register: vault_encryption
          changed_when: vault_encryption.rc == 0
          failed_when: vault_encryption.rc !=0 and "ERROR! input is not vault encrypted" not in vault_encryption.stderr

    - name: Generate/Renew SSL certs for {{ fqdn }}
      include_role:
        name: ansible-role-lets-encrypt-route-53
      vars:
        ler53_cert_common_name: "{{ fqdn }}"

    - name: Encrypt the private keys
      block:
        - name: Find all sensitive files
          find:
            paths: "{{ ler53_account_key_dir }}"
            file_type: file
            patterns:
              - "{{ fqdn }}.key"
            recurse: true
            depth: 2
          register: keys
        - name: Encrypt the sensitive files
          command: "ansible-vault encrypt {{ item.path }} --vault-password-file {{ playbook_dir | dirname }}/.vault_password"
          with_items: "{{ keys.files | flatten(levels=1) }}"
          register: vault_encryption
          changed_when: vault_encryption.rc == 0
          failed_when: vault_encryption.rc !=0 and vault_encryption.stderr != "ERROR! input is already encrypted"
